#include <vector>
#include <list>
#include <map>
#include <set>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <climits>

using namespace std;

#define PI 3.14159265359
#define REP(i,n) for(LL i=0;i<(n);++i)
#define FOR(i,k,n) for (LL i=(k); i<=(LL)(n); ++i)
#define X first
#define Y second
#define CLR(x) memset((x), 0, sizeof(x))
#define PB push_back
#define MP make_pair
typedef pair<int, int> PII;
typedef vector<int> VI;
typedef long long LL;
typedef long double LD;

class Egalitarianism {
public:
	int maxDifference(vector <string>, int);
	LL dis[55][55];
};

int Egalitarianism::maxDifference(vector <string> isFriend, int d) {
	int num=isFriend.size();
	REP(i,num)REP(j,num){
		if(i==j)dis[i][i]=0;
		else if(isFriend[i][j]=='Y')dis[i][j]=1;
		else dis[i][j]=INT_MAX;
	}
	REP(i,num)REP(j,num)REP(k,num){
		dis[j][k]=min(dis[j][k],dis[j][i]+dis[i][k]);
	}
	LL ans=0;
	REP(i,num)REP(j,num)ans=max(ans,dis[i][j]);
	if(ans==INT_MAX)return -1;
	return ans*d;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, int p1, bool hasAnswer, int p2) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << p1;
	cout << "]" << endl;
	Egalitarianism *obj;
	int answer;
	obj = new Egalitarianism();
	clock_t startTime = clock();
	answer = obj->maxDifference(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p2 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	int p2;
	
	{
	// ----- test 0 -----
	string t0[] = {"NYN","YNY","NYN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 10;
	p2 = 20;
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"NN","NN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	p2 = -1;
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"NNYNNN","NNYNNN","YYNYNN","NNYNYY","NNNYNN","NNNYNN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1000;
	p2 = 3000;
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"NNYN","NNNY","YNNN","NYNN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 584;
	p2 = -1;
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"NYNYYYN","YNNYYYN","NNNNYNN","YYNNYYN","YYYYNNN","YYNYNNY","NNNNNYN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 5;
	p2 = 20;
	all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	string t0[] = {"NYYNNNNYYYYNNNN","YNNNYNNNNNNYYNN","YNNYNYNNNNYNNNN","NNYNNYNNNNNNNNN","NYNNNNYNNYNNNNN","NNYYNNYNNYNNNYN","NNNNYYNNYNNNNNN","YNNNNNNNNNYNNNN","YNNNNNYNNNNNYNN","YNNNYYNNNNNNNNY","YNYNNNNYNNNNNNN","NYNNNNNNNNNNNNY","NYNNNNNNYNNNNYN","NNNNNYNNNNNNYNN","NNNNNNNNNYNYNNN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 747;
	p2 = 2988;
	all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	{
	// ----- test 6 -----
	string t0[] = {"NY","YN"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0;
	p2 = 0;
	all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// A kingdom has n citizens. Each one has some amount of money, a number of dollars denoted by a non-negative integer.
// 
// Citizens are numbered from 0 to n-1. Some citizens have friends. Their friendship network is described by a vector <string> called isFriend, such that if isFriend[i][j] == 'Y', the citizens numbered i and j are friends, and if isFriend[i][j] == 'N', these citizens are not friends.
// 
// The king decrees the following:
// 
// Each citizen's amount of money must be within d dollars of the amount of money belonging to any of his friends. In other words, a citizen with x dollars must not have any friends with less than x-d dollars or more than x+d dollars.
// 
// Given the number of citizens and their friendship network, what is the greatest possible money difference between any two people (not necessarily friends) in this kingdom? If there is a finite answer, return it. Otherwise, return -1.
// 
// DEFINITION
// Class:Egalitarianism
// Method:maxDifference
// Parameters:vector <string>, int
// Returns:int
// Method signature:int maxDifference(vector <string> isFriend, int d)
// 
// 
// CONSTRAINTS
// -n will be between 2 and 50, inclusive.
// -d will be between 0 and 1,000, inclusive.
// -isFriend will contain exactly n elements.
// -Each element of isFriend will contain exactly n characters, each of which is either 'Y' or 'N'.
// -For any i, isFriend[i][i] = 'N'.
// -For any i and j, isFriend[i][j] = isFriend[j][i].
// 
// 
// EXAMPLES
// 
// 0)
// {"NYN",
//  "YNY",
//  "NYN"}
// 10
// 
// Returns: 20
// 
// The kingdom has three citizens. Citizens 0 and 1 are friends. Also, citizens 1 and 2 are friends. The greatest possible money difference between any two citizens is $20, as in the following configuration: citizen 0 has $100; citizen 1 has $110; citizen 2 has $120.
// 
// 1)
// {"NN",
//  "NN"}
// 1
// 
// Returns: -1
// 
// Since citizens 0 and 1 are not friends, there are no constraints between them.
// 
// 2)
// {"NNYNNN",
//  "NNYNNN",
//  "YYNYNN",
//  "NNYNYY",
//  "NNNYNN",
//  "NNNYNN"}
// 1000
// 
// Returns: 3000
// 
// 
// 
// 3)
// {"NNYN",
//  "NNNY",
//  "YNNN",
//  "NYNN"}
// 584
// 
// Returns: -1
// 
// 
// 
// 4)
// {"NYNYYYN",
//  "YNNYYYN",
//  "NNNNYNN",
//  "YYNNYYN",
//  "YYYYNNN",
//  "YYNYNNY",
//  "NNNNNYN"}
// 5
// 
// Returns: 20
// 
// 
// 
// 5)
// {"NYYNNNNYYYYNNNN",
//  "YNNNYNNNNNNYYNN",
//  "YNNYNYNNNNYNNNN",
//  "NNYNNYNNNNNNNNN",
//  "NYNNNNYNNYNNNNN",
//  "NNYYNNYNNYNNNYN",
//  "NNNNYYNNYNNNNNN",
//  "YNNNNNNNNNYNNNN",
//  "YNNNNNYNNNNNYNN",
//  "YNNNYYNNNNNNNNY",
//  "YNYNNNNYNNNNNNN",
//  "NYNNNNNNNNNNNNY",
//  "NYNNNNNNYNNNNYN",
//  "NNNNNYNNNNNNYNN",
//  "NNNNNNNNNYNYNNN"}
// 
// 747
// 
// Returns: 2988
// 
// 
// 
// 6)
// {"NY",
//  "YN"}
// 0
// 
// Returns: 0
// 
// 
// 
// END KAWIGIEDIT TESTING

//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
